name: Greenlands

on:
  push:
    branches:
      - master

  schedule:
    - cron: '0 0,12 * * *'

jobs:
  greenlands:
    runs-on: ubuntu-latest
    steps:
      - name : global directory
        run: git config --global --add safe.directory /github/workspace
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: Modify last update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit changes
        run: |
          git config --local user.email "kingkinfajar8@gmail.com"
          git config --local user.name "kingkinfajarr"
          git add -A

          arr[0]="feat: 🚀 greenlands"
          arr[1]="feat: 🌴 greenlands"
          arr[2]="feat: 🤙 greenlands"
          arr[3]="feat: ✅ greenlands"
          arr[4]="feat: 🌱 greenlands"
          
          rand=$[$RANDOM % ${#arr[@]}]
          
          git commit -m "${arr[$rand]}"

      - name: Github Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
